name: deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  node_test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0.0
      - run: deno lint
      - run: deno fmt
      - run: deno test
